docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v3
  versions:
    - v3
nav:
  - Home: index.md
  - v3:
      - Configuration: v3/configuration.md
      - Installation: v3/installation.md
      - "Manage GeoLite2 database": v3/manage-geolite2-database.md
      - Usage: v3/usage.md
site_name: dot-geoip
site_description: "DotKernel's component to provide geographical details about an IP address"
repo_url: "https://github.com/dotkernel/dot-geoip"
plugins:
  - search
